version: '3.7'

services:


  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Kocyk123!
      MYSQL_DATABASE: fast_serwis
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Kocyk123!

  fast-service-backend:
    container_name: fast-service-app
    restart: on-failure
    image: fast-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fast_serwis?rewriteBatchedStatements=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&connectionTimeZone=Europe/Warsaw&serverTimezone=UTC
    ports:
      - "8085:8085"
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql:
