
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/fast_serwis?rewriteBatchedStatements=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&connectionTimeZone=Europe/Warsaw&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

    #        generate_statistics: true
    show-sql: true
page:
  size: 7

thymeleaf:
  version: 3.0.2.RELEASE
thymeleaf-layout-dialect:
  version: 2.1.1

logging:
  level:
    org.springframework.security: DEBUG